//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginManager.Console.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginManager.Console.Resources.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies found (Count: {0}, Assemblies: {1}).
        /// </summary>
        internal static string AssembliesFound {
            get {
                return ResourceManager.GetString("AssembliesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly {0} has been loaded.
        /// </summary>
        internal static string AssemblyLoaded {
            get {
                return ResourceManager.GetString("AssemblyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLL {0} or executable program is not valid ({1}).
        /// </summary>
        internal static string BadImageException {
            get {
                return ResourceManager.GetString("BadImageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed.
        /// </summary>
        internal static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished downloading DLL: {0}.
        /// </summary>
        internal static string DownloadFinished {
            get {
                return ResourceManager.GetString("DownloadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading DLL: {0}. Download API method: {1}.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting download....
        /// </summary>
        internal static string DownloadStart {
            get {
                return ResourceManager.GetString("DownloadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load file or assembly {0} ({1}).
        /// </summary>
        internal static string FileLoadExeption {
            get {
                return ResourceManager.GetString("FileLoadExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------.
        /// </summary>
        internal static string LineSeparator {
            get {
                return ResourceManager.GetString("LineSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local assemblies not found.
        /// </summary>
        internal static string LocalAssembliesNotFound {
            get {
                return ResourceManager.GetString("LocalAssembliesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} has been executed.
        /// </summary>
        internal static string MethodExecuted {
            get {
                return ResourceManager.GetString("MethodExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing method {0}.
        /// </summary>
        internal static string MethodExecuting {
            get {
                return ResourceManager.GetString("MethodExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T must be an interface.
        /// </summary>
        internal static string NotInterfaceException {
            get {
                return ResourceManager.GetString("NotInterfaceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed download: Plugin {0}. Reason: {1}.
        /// </summary>
        internal static string PluginDownloadFail {
            get {
                return ResourceManager.GetString("PluginDownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success download: Plugin {0}.
        /// </summary>
        internal static string PluginDownloadSuccess {
            get {
                return ResourceManager.GetString("PluginDownloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins not available.
        /// </summary>
        internal static string PluginsNotAvailable {
            get {
                return ResourceManager.GetString("PluginsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: FAILED, StatusCode: {0}, Reason: {1}, Result: {2}.
        /// </summary>
        internal static string ProcessFail {
            get {
                return ResourceManager.GetString("ProcessFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}.
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates found: {0}.
        /// </summary>
        internal static string UpdateFound {
            get {
                return ResourceManager.GetString("UpdateFound", resourceCulture);
            }
        }
    }
}
